In [1]:
using Flux: gradient

In [7]:
f(x) = 3x^2 + 2x + 1

println(f(5))

86


In [16]:
# First order derivative
df(x) = gradient(f, x)[1]

println(df(5))

# Sceond order derivative
ddf(x) = gradient(df, x)

println(ddf(5))

# For the first time, it takes some time.
# After that, these calculations are cached.

32.0
(6.0,)


In [23]:
myloss(W, b, x) = sum(W * x .+ b)

myloss (generic function with 1 method)

In [24]:
W = randn(3, 5)
b = zeros(3)
x = rand(5)

5-element Vector{Float64}:
 0.3676631404205277
 0.8902956739591973
 0.1255853697738113
 0.11270827648041404
 0.5502044923936937

In [37]:
W

3×5 Matrix{Float64}:
  0.992179  -1.02181   -1.46398    1.39222   -0.00383902
 -1.06775   -0.180947   0.616928  -0.253127  -1.42683
  1.5716    -0.560059  -0.332651   0.158226   1.59936

In [38]:
b

3-element Vector{Float64}:
 0.0
 0.0
 0.0

In [39]:
x

5-element Vector{Float64}:
 0.3676631404205277
 0.8902956739591973
 0.1255853697738113
 0.11270827648041404
 0.5502044923936937

In [67]:
# Gradient wrt W = xᵀ .+ b
gradient(myloss, W, b, x)[1]

3×5 Matrix{Float64}:
 0.367663  0.890296  0.125585  0.112708  0.550204
 0.367663  0.890296  0.125585  0.112708  0.550204
 0.367663  0.890296  0.125585  0.112708  0.550204

In [68]:
x' .+ b

3×5 Matrix{Float64}:
 0.367663  0.890296  0.125585  0.112708  0.550204
 0.367663  0.890296  0.125585  0.112708  0.550204
 0.367663  0.890296  0.125585  0.112708  0.550204

In [69]:
# Gradient wrt b = 1
gradient(myloss, W, b, x)[2]

3-element Fill{Float64}, with entries equal to 1.0

In [75]:
using Flux: params

W = randn(3, 5)
b = zeros(3)
x = rand(5)

y(x) = sum(W * x .+ b)

grads = gradient(()->y(x), params([W, b]))

Grads(...)

In [78]:
grads[W]

3×5 Matrix{Float64}:
 0.659177  0.0569233  0.623368  0.616565  0.15328
 0.659177  0.0569233  0.623368  0.616565  0.15328
 0.659177  0.0569233  0.623368  0.616565  0.15328

In [79]:
grads[b]

3-element Fill{Float64}, with entries equal to 1.0

In [129]:
using Flux
m = Dense(10, 5)
x = rand(Float32, 10)

10-element Vector{Float32}:
 0.37222153
 0.60511893
 0.24287015
 0.20751816
 0.48786706
 0.93959624
 0.39977288
 0.43573952
 0.5225794
 0.25934428

In [130]:
params(m)[1]

5×10 Matrix{Float32}:
 -0.498481   0.41813     0.346584   …   0.0968794  -0.488937   -0.154911
  0.395868  -0.401942    0.410465       0.341339    0.264836   -0.576389
 -0.300246  -0.0721001  -0.273318      -0.0573174  -0.0249172  -0.384246
  0.551283   0.541708    0.464189      -0.313076   -0.560357    0.0229575
 -0.423883  -0.264012    0.0208688     -0.204324    0.45719     0.255334

In [131]:
params(m)[2]

5-element Vector{Float32}:
 0.0
 0.0
 0.0
 0.0
 0.0